const fs = require("fs");
const path = require("path");

const rootDir = path.dirname(__dirname);
const srcDir = `${rootDir}/js/i18n/locales`;
const distDir = `${rootDir}/dist/js/locales`;

// Prepare target directory
if (fs.existsSync(distDir)) {
  fs.readdirSync(distDir).forEach((file) =>
    fs.unlinkSync(`${distDir}/${file}`)
  );
} else {
  fs.mkdirSync(distDir, { recursive: true });
}

fs.readdirSync(srcDir).forEach((file) => {
  const src = fs.readFileSync(`${srcDir}/${file}`, "utf8");

  // Extract the language code from the file name (e.g. ‘pl.js’ -> ‘pl’)
  const localeName = path.basename(file, ".js");

  // Extract the content of the location object
  const match = src.match(
    /export default \{\s*[\w'-]+:\s*(\{[\s\S]+?\})\s*\};/m
  );

  if (match) {
    const localeData = match[1];

    const output = `/**
 * Locale: ${localeName}
 * Generated by build-locales.js
 */
export default ${localeData};`;

    fs.writeFileSync(`${distDir}/${file}`, output);
  } else {
    fs.copyFileSync(`${srcDir}/${file}`, `${distDir}/${file}`);
  }
});
